export const Z_INDEX = {
  base: 'z-0',
  content: 'z-10',
  cardOverlay: 'z-20',
  dropdown: 'z-40',
  stickyNav: 'z-50',
  tooltip: 'z-50',
  loadingBar: 'z-[52]',
  skipLink: 'z-[55]',
  readingProgress: 'z-[54]',
  mobileNavOverlay: 'z-[55]',
  mobileNav: 'z-[57]',
  cookieConsent: 'z-[58]',
  modalBackdrop: 'z-[60]',
  drawerPanel: 'z-[65]',
  prompts: 'z-[70]',
  shareMenu: 'z-[90]',
  offlineBanner: 'z-[92]',
  popover: 'z-[95]',
  toast: 'z-[100]',
  shortcutBackdrop: 'z-[110]',
  shortcutWidget: 'z-[111]',
  adminModal: 'z-[120]',
} as const;
